# Generated by Django 2.2 on 2020-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адресс')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('product', models.ManyToManyField(related_name='order_product', to='webapp.Product', verbose_name='Продукты')),
            ],
        ),
    ]
