# Generated by Django 2.2 on 2020-09-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200920_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='qty',
            new_name='amount',
        ),
    ]
